const empleados_faltantes = [
  {
    empresa: "Ecolarva",
    codigo_empleado: "FAL01",
    cedula: "jerfalcon",
    clave: "7639755",
    nombres: "José Enrique",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Pesca Atlantico Ca",
    codigo_empleado: "LACA01",
    cedula: "jerlacanada",
    clave: "7639755",
    nombres: "José Enrique",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Palmeras Lago Maracaibo Ca",
    codigo_empleado: "MACH01",
    cedula: "jermachiques",
    clave: "7639755",
    nombres: "José Enrique",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Reco Reciclajes Ecologicos Sa",
    codigo_empleado: "MCBO01",
    cedula: "jermaracaibo",
    clave: "7639755",
    nombres: "José Enrique",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Industria Marina De Alimentos",
    codigo_empleado: "SFCO01",
    cedula: "jersanfrancisco",
    clave: "7639755",
    nombres: "José Enrique",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Acuicultivo Coquivacoa Ca",
    codigo_empleado: "SDL01",
    cedula: "jersurdellago",
    clave: "7639755",
    nombres: "José Enrique",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Corporativo",
    codigo_empleado: "CORP01",
    cedula: "jercorporativo",
    clave: "7639755",
    nombres: "José Enrique",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Corporativo",
    codigo_empleado: "CORP02",
    cedula: "18664479",
    clave: "18664479",
    nombres: "Juan Diego",
    apellidos: "Rincón Sabatino",
    fecha_nacimiento: "2000-01-01",
  },
  {
    empresa: "Corporativo",
    codigo_empleado: "CORP03",
    cedula: "17948627",
    clave: "17948627",
    nombres: "José Junior",
    apellidos: "Rincón",
    fecha_nacimiento: "2000-01-01",
  },
];

module.exports = {
  empleados_faltantes,
};
