const partidos = [
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "Argentina",
    equipo_b: "Canadá",
    fecha_hora_partido: "2024-06-20 20:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "Perú",
    equipo_b: "Chile",
    fecha_hora_partido: "2024-06-21 20:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "Ecuador",
    equipo_b: "Venezuela",
    fecha_hora_partido: "2024-06-22 18:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "México",
    equipo_b: "Jamaica",
    fecha_hora_partido: "2024-06-22 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "Estados Unidos",
    equipo_b: "Bolivia",
    fecha_hora_partido: "2024-06-23 18:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "Uruguay",
    equipo_b: "Panamá",
    fecha_hora_partido: "2024-06-23 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "Colombia",
    equipo_b: "Paraguay",
    fecha_hora_partido: "2024-06-24 18:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "1",
    equipo_a: "Brasil",
    equipo_b: "Costa Rica",
    fecha_hora_partido: "2024-06-24 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Perú",
    equipo_b: "Canadá",
    fecha_hora_partido: "2024-06-25 18:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Chile",
    equipo_b: "Argentina",
    fecha_hora_partido: "2024-06-25 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Ecuador",
    equipo_b: "Jamaica",
    fecha_hora_partido: "2024-06-26 18:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Venezuela",
    equipo_b: "México",
    fecha_hora_partido: "2024-06-26 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Panamá",
    equipo_b: "Estados Unidos",
    fecha_hora_partido: "2024-06-27 18:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Uruguay",
    equipo_b: "Bolivia",
    fecha_hora_partido: "2024-06-27 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Colombia",
    equipo_b: "Costa Rica",
    fecha_hora_partido: "2024-06-28 18:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "2",
    equipo_a: "Paraguay",
    equipo_b: "Brasil",
    fecha_hora_partido: "2024-06-28 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "Argentina",
    equipo_b: "Perú",
    fecha_hora_partido: "2024-06-29 20:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "Canadá",
    equipo_b: "Chile",
    fecha_hora_partido: "2024-06-29 20:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "México",
    equipo_b: "Ecuador",
    fecha_hora_partido: "2024-06-30 20:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "Jamaica",
    equipo_b: "Venezuela",
    fecha_hora_partido: "2024-06-30 20:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "Bolivia",
    equipo_b: "Panamá",
    fecha_hora_partido: "2024-07-01 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "Estados Unidos",
    equipo_b: "Uruguay",
    fecha_hora_partido: "2024-07-01 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "Brasil",
    equipo_b: "Colombia",
    fecha_hora_partido: "2024-07-02 21:00:00",
  },
  {
    tipo_partido: "Fase de grupos",
    numero_jornada: "3",
    equipo_a: "Costa Rica",
    equipo_b: "Paraguay",
    fecha_hora_partido: "2024-07-02 21:00:00",
  },
];

module.exports = {
  partidos,
};
